import os
import glob
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv
import json
from concurrent.futures import ThreadPoolExecutor

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

RAW_DIR = r"data/raw/profil kesehatan_nasional_kemenkes"
IN_PROCESSED = r"data/processed/sulawesi_faskes_agregat_v2.csv"
OUT_PROCESSED = r"data/processed/sulawesi_faskes_agregat_v2.csv"
PROVINCES = ["Gorontalo", "Sulawesi Tengah", "Sulawesi Tenggara", "Sulawesi Selatan", "Sulawesi Utara", "Sulawesi Barat"]

def is_proxy_row(row):
    # If it was generated by the previous fallback
    if row.get('sumber_file') == 'Proxy Nasional (Markdown dengan Fallback Alignment)':
        return True
    # Or if it was generated by the older v1 proxy
    kutipan = str(row.get('sumber_kutipan', '')).strip().lower()
    if kutipan.startswith("berdasarkan tabel") or "tabel x" in kutipan or "posisi ke-" in kutipan or "urutan ke-" in kutipan or "rusak" in kutipan:
        return True
    return False

def extract_chunks_from_md(filepath):
    chunks = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f: lines = f.readlines()
    except:
        with open(filepath, 'r', encoding='latin-1') as f: lines = f.readlines()
            
    chunk_size = 3500
    overlap = 500
    i = 0
    while i < len(lines):
        end = min(i + chunk_size, len(lines))
        chunk_lines = lines[i:end]
        chunk_text = "\n".join(chunk_lines).lower()
        
        has_prov = any(prov.lower() in chunk_text for prov in PROVINCES)
        has_kw = "puskesmas" in chunk_text or "rumah sakit" in chunk_text
        
        if has_prov and has_kw:
            chunks.append({
                "lines": chunk_lines,
                "start_baris": i + 1,
                "sumber_file": os.path.basename(filepath)
            })
        i += (chunk_size - overlap)
    return chunks

def process_year(tahun, missing_combos):
    md_file = os.path.join(RAW_DIR, f"profil-kesehatan-indonesia-{tahun}.md")
    if not os.path.exists(md_file):
        possible_files = glob.glob(os.path.join(RAW_DIR, f"*{tahun}*.md"))
        if not possible_files: return []
        md_file = possible_files[0]
        
    print(f"Mengekstrak {tahun} dari {os.path.basename(md_file)}...")
    chunks = extract_chunks_from_md(md_file)
    extracted = []
    
    def analyze_chunk(chunk):
        context_lines = [f"[{chunk['start_baris'] + j}] {line.strip()}" for j, line in enumerate(chunk['lines']) if line.strip()]
        context_text = "\n".join(context_lines)
        
        missing_str = ", ".join([f"{p} ({j})" for p, j in missing_combos])
        prompt = f"""Anda adalah Auditor Data Forensik Senior Kemenkes yang SANGAT KETAT dan TANPA KOMPROMI.
Tugas: Temukan TOTAL PUSKESMAS dan TOTAL RUMAH SAKIT untuk provinsi berikut:
{missing_str}

Teks di bawah kemungkinan besar adalah tabel PDF yang rusak saat di-convert ke Markdown (misal: deretan angka dipisah `<br><br>`, lalu deretan provinsi di bawahnya).

ATURAN EKSTRAKSI (WAJIB DIIKUTI 100%):
1. Anda WAJIB menemukan dan mencocokkan angka absolut untuk Faskes (Puskesmas / Rumah Sakit) untuk provinsi yang diminta, BAGAIMANAPUN KONDISI TABELNYA.
2. JANGAN PERNAH MENGOSONGKAN HASIL. Jika ada deretan angka yang sepertinya berhubungan dengan Faskes, pasangkan urutannya dengan deretan provinsi di bawahnya secara logis! Jika Anda harus menebak dari data yang tidak beraturan, TEBAKLAH DENGAN PINTAR.
3. Anda harus memberikan ALASAN EKSTRAKSI yang sangat eksplisit secara tekstual. Jangan sekadar menulis "Posisi ke-3". Anda harus menulis seperti: "Ditemukan deretan angka absolut Puskesmas di mana angka 98 berada di urutan ke-3, yang selaras persis dengan nama Sulawesi Barat di urutan ke-3 pada deretan provinsi di bawahnya."

Format JSON (WAJIB array):
[
  {{"provinsi": "Sulawesi Selatan", "jenis": "Puskesmas", "jumlah": 460, "alasan_ekstraksi": "Tabel memuat daftar jumlah absolut Puskesmas per provinsi. Angka 460 sejajar dengan Sulawesi Selatan di urutan ke-24.", "angka_start_baris": 1400, "angka_end_baris": 1405, "provinsi_start_baris": 1420, "provinsi_end_baris": 1425}}
]

TEKS SUMBER (Profil {tahun}):
{context_text}"""
        try:
            res = client.chat.completions.create(
                model="gpt-5.4-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0, max_completion_tokens=1500
            )
            raw = res.choices[0].message.content.strip()
            if raw.startswith('```json'): raw = raw[7:-3]
            elif raw.startswith('```'): raw = raw[3:-3]
            data = json.loads(raw)
            valid_res = []
            
            # Inject raw text based on line indices
            for d in data:
                prov = d.get('provinsi')
                jns = d.get('jenis')
                if (prov, jns) in missing_combos:
                    start_a = d.get('angka_start_baris', 0)
                    end_a = d.get('angka_end_baris', 0)
                    start_p = d.get('provinsi_start_baris', 0)
                    end_p = d.get('provinsi_end_baris', 0)
                    
                    raw_quote = ""
                    # Find lines in context
                    for line in context_lines:
                        line_num = int(line.split(']')[0][1:])
                        if start_a <= line_num <= end_a:
                            raw_quote += line + "\n"
                    raw_quote += "\n[...]\n\n"
                    for line in context_lines:
                        line_num = int(line.split(']')[0][1:])
                        if start_p <= line_num <= end_p:
                            raw_quote += line + "\n"
                            
                    d['sumber_kutipan'] = raw_quote
                    d['baris_md'] = start_a
                    valid_res.append(d)
            return valid_res
        except Exception as e:
            print(f"API Error with gpt-5.4-mini: {e}")
            return []

    with ThreadPoolExecutor(max_workers=10) as executor:
        for res in executor.map(analyze_chunk, chunks):
            if res: extracted.extend(res)
            
    final_for_year = []
    seen = set()
    for item in extracted:
        key = (item['provinsi'], item['jenis'])
        if key not in seen and item.get('jumlah') is not None:
            seen.add(key)
            item['tahun'] = tahun
            final_for_year.append(item)
    return final_for_year

def main():
    print("Membaca base data v2...")
    df = pd.read_csv(IN_PROCESSED)
    
    valid_mask = ~df.apply(is_proxy_row, axis=1)
    df_valid = df[valid_mask].copy()
    
    existing = set(zip(df_valid['tahun'].astype(int), df_valid['provinsi'], df_valid['jenis']))
    
    years = range(2014, 2025)
    jenis_faskes = ["Puskesmas", "Rumah Sakit"]
    missing_dict = {y: [] for y in years}
    
    for y in years:
        for p in PROVINCES:
            for j in jenis_faskes:
                if (y, p, j) not in existing:
                    missing_dict[y].append((p, j))
                    
    new_records = []
    for y, combos in missing_dict.items():
        if combos:
            res = process_year(y, combos)
            new_records.extend(res)
            
    if new_records:
        for r in new_records:
            r['sumber_file'] = 'Proxy Nasional (Markdown dengan Fallback Alignment)'
        df_new = pd.DataFrame(new_records)
        df_new = df_new[['tahun', 'provinsi', 'jenis', 'jumlah', 'baris_md', 'sumber_kutipan', 'sumber_file']]
        
        if 'sumber_file' not in df_valid.columns:
            df_valid['sumber_file'] = 'Profil Provinsi Lokal'
            
        df_final = pd.concat([df_valid, df_new], ignore_index=True)
        df_final = df_final.sort_values(by=['provinsi', 'tahun', 'jenis']).reset_index(drop=True)
        df_final.to_csv(OUT_PROCESSED, index=False)
        print(f"\nBerhasil menambahkan {len(df_new)} baris proxy ke {OUT_PROCESSED}")
    else:
        print("\nTidak ada data yang berhasil diekstrak.")

if __name__ == "__main__":
    main()
